# Rezultat crawler pentru testare BD

name = ['Jeff Bezos ', 'Elon Musk ', 'Bernard Arnault & family ', 'Bill Gates ', 'Mark Zuckerberg ', 'Warren Buffett ',
        'Larry Ellison ', 'Larry Page ', 'Sergey Brin ', 'Mukesh Ambani ', 'Amancio Ortega ',
        'Francoise Bettencourt Meyers & family ', 'Zhong Shanshan ', 'Steve Ballmer ', 'Ma Huateng ',
        'Carlos Slim Helu & family ', 'Alice Walton ', 'Jim Walton ', 'Rob Walton ', 'Michael Bloomberg ',
        'Colin Zheng Huang ', 'MacKenzie Scott ', 'Daniel Gilbert ', 'Gautam Adani & family ', 'Phil Knight & family ',
        'Jack Ma ', 'Charles Koch ', 'Julia Koch & family ', 'Masayoshi Son ', 'Michael Dell ',
        'Tadashi Yanai & family ', 'François Pinault & family ', 'David Thomson & family ',
        'Beate Heister & Karl Albrecht Jr. ', 'Wang Wei ', 'Miriam Adelson ', 'He Xiangjian ', 'Dieter Schwarz ',
        'Zhang Yiming ', 'Giovanni Ferrero ', 'Alain Wertheimer ', 'Gerard Wertheimer ', 'Li Ka-shing ',
        'Qin Yinglin & family ', 'William Lei Ding ', 'Len Blavatnik ', 'Lee Shau Kee ', 'Jacqueline Mars ',
        'John Mars ', 'Yang Huiyan & family ', 'Alexey Mordashov & family ', 'Robin Zeng ', 'Hui Ka Yan ',
        'Susanne Klatten ', 'Vladimir Potanin ', 'Dietrich Mateschitz ', 'Pang Kang ', 'Klaus-Michael Kuehne ',
        'Vladimir Lisin ', 'Wang Xing ', 'German Larrea Mota Velasco & family ', 'Leonardo Del Vecchio & family ',
        'Takemitsu Takizaki ', 'Leonard Lauder ', 'Thomas Peterffy ', 'Vagit Alekperov ', 'Leonid Mikhelson ',
        'Jim Simons ', 'Jiang Rensheng & family ', 'Gina Rinehart ', 'Rupert Murdoch & family ', 'Shiv Nadar ',
        'Zhang Zhidong ', 'Iris Fontbona & family ', 'Lei Jun ', 'Zhang Yong ', 'Richard Qiangdong Liu ',
        'Gennady Timchenko ', 'Stephen Schwarzman ', 'Goh Cheng Liang ', 'Stefan Quandt ', 'Li Xiting ',
        'Pierre Omidyar ', 'Stefan Persson ', 'Abigail Johnson ', 'R. Budi Hartono ', 'Andrew Forrest ', 'Ray Dalio ',
        'Michael Hartono ', 'Li Shufu ', 'Zhong Huijuan ', 'Xu Hang ', 'Lui Che Woo & family ', 'Emmanuel Besnier ',
        'Laurene Powell Jobs & family ', 'Eric Schmidt ', 'Sun Piaoyang ', 'Theo Albrecht, Jr. & family ',
        'Alisher Usmanov ', 'Robert Pera ', 'Wu Yajun ', 'Fan Hongwei & family ', 'Dhanin Chearavanont ', 'Peter Woo ',
        'Chen Bang ', 'Andrey Melnichenko ', 'Dustin Moskovitz ', 'Su Hua ', 'Donald Newhouse ', 'Petr Kellner ',
        'Lee Man Tat ', 'Pavel Durov ', 'James Ratcliffe ', 'Jorge Paulo Lemann & family ', 'Reinhold Wuerth & family ',
        'Charlene de Carvalho-Heineken & family ', 'Radhakishan Damani ', 'Wang Chuanfu ', 'Steve Cohen ',
        'Ken Griffin ', 'Chen Zhiping ', 'Ernest Garcia, II. ', 'Uday Kotak ', 'Carl Icahn ',
        'Suleiman Kerimov & family ', 'Thomas Frist, Jr. & family ', 'Lukas Walton ', 'Mikhail Fridman ',
        'Wei Jianjun & family ', 'Zuo Hui ', 'Zhou Qunfei & family ', 'Donald Bren ', 'Hinduja brothers ',
        'Lakshmi Mittal ', 'Georg Schaeffler ', 'Eric Yuan & family ', 'Wang Jianlin ', 'Kwong Siu-hing ', 'Robin Li ',
        'Pallonji Mistry ', 'Eduardo Saverin ', 'Roman Abramovich ', 'David Tepper ', 'Gong Hongjia & family ',
        'Mike Cannon-Brookes ', 'John Menard, Jr. ', 'Seo Jung-jin ', 'Cheng Yixiao ', 'Liang Wengen ',
        'Scott Farquhar ', 'Finn Rausing ', 'Jorn Rausing ', 'Kirsten Rausing ', 'Brian Chesky ', 'Joseph Lau ',
        'David Duffield ', 'Charoen Sirivadhanabhakdi ', 'Kim Jung-ju ', 'Robert & Philip Ng ', 'Zhang Bangxin ',
        'Anders Holch Povlsen ', 'Wang Wenyin ', 'Wang Liping & family ', 'Tatyana Bakalchuk ', 'Michael Platt ',
        'Huang Shilin ', 'Ricardo Salinas Pliego & family ', 'Kumar Birla ', 'Dang Yanbao ', 'Cyrus Poonawalla ',
        'Robert Kuok ', 'Hank & Doug Meijer ', 'Jack Dorsey ', 'Lu Zhongfang ', 'Ma Jianrong & family ', 'Zhang Tao ',
        'Nathan Blecharczyk ', 'John Doerr ', 'Joe Gebbia ', 'Forrest Li ', 'Yu Renrong ', 'Liu Yonghao & family ',
        'Gordon Moore ', 'Jeff Yass ', 'Bobby Murphy ', 'Patrick Drahi ', 'Jensen Huang ', 'Alexander Otto ',
        'Cen Junda ', 'Joseph Tsai ', 'Aliko Dangote ', 'Marcel Herrmann Telles ', 'Mikhail Prokhorov ',
        'Jorge Moll Filho & family ', 'Viktor Rashnikov ', 'Harry Triguboff ', 'Leonid Fedun & family ', 'Eyal Ofer ',
        'Evan Spiegel ', 'Luis Carlos Sarmiento ']
age = ['57', '50', '72', '66', '37', '91', '77', '48', '48', '64', '85', '68', '67', '65', '50', '81', '72', '73', '77',
       '79', '41', '51', '59', '59', '83', '57', '86', '59', '64', '56', '72', '85', '64', None, '51', '76', '79', '82',
       '37', '57', '73', '70', '93', '56', '50', '64', '93', '82', '86', '40', '56', '52', '63', '59', '60', '77', '65',
       '84', '65', '42', '68', '86', '76', '88', '77', '71', '66', '83', '68', '67', '90', '76', '49', '78', '51', '51',
       '47', '69', '74', '94', '55', '70', '54', '74', '59', '80', '60', '72', '82', '58', '60', '55', '92', '51', '58',
       '66', '63', '70', '68', '43', '57', '54', '82', '75', '56', '49', '37', '39', '92', None, None, '37', '68', '82',
       '86', '67', '66', '55', '65', '53', '45', '64', '62', '85', '55', '83', '35', '57', '57', None, None, '89', None,
       '71', '57', '51', '67', '92', '53', '92', '39', '55', '64', '56', '42', '81', '64', '37', '64', '41', '66', '61',
       '69', '40', '70', '81', '77', '53', None, '41', '49', '53', '55', '46', '53', '54', '66', '54', '48', '80', '98',
       None, '45', '79', '57', '49', '38', '70', '40', '43', '55', '70', '92', '63', '33', '58', '58', '54', '57', '57',
       '64', '71', '56', '76', '73', '88', '65', '71', '31', '88']
source_of_wealth = ['Amazon, Self Made', 'Tesla, SpaceX, Self Made', 'LVMH', 'Microsoft, Self Made',
                    'Facebook, Self Made', 'Berkshire Hathaway, Self Made', 'software, Self Made', 'Google, Self Made',
                    'Google, Self Made', 'diversified', 'Zara, Self Made', "L'Oréal",
                    'beverages, pharmaceuticals, Self Made', 'Microsoft, Self Made', 'internet media, Self Made',
                    'telecom, Self Made', 'Walmart', 'Walmart', 'Walmart', 'Bloomberg LP, Self Made',
                    'e-commerce, Self Made', 'Amazon', 'Quicken Loans, Self Made',
                    'infrastructure, commodities, Self Made', 'Nike, Self Made', 'e-commerce, Self Made',
                    'Koch Industries', 'Koch Industries', 'internet, telecom, Self Made', 'Dell computers, Self Made',
                    'fashion retail, Self Made', 'luxury goods, Self Made', 'media', 'supermarkets',
                    'package delivery, Self Made', 'casinos', 'home appliances, Self Made', 'retail',
                    'TikTok, Self Made', 'Nutella, chocolates', 'Chanel', 'Chanel', 'diversified, Self Made',
                    'pig breeding, Self Made', 'online games, Self Made', 'music, chemicals, Self Made',
                    'real estate, Self Made', 'candy, pet food', 'candy, pet food', 'real estate',
                    'steel, investments, Self Made', 'batteries, Self Made', 'real estate, Self Made',
                    'BMW, pharmaceuticals', 'metals, Self Made', 'Red Bull, Self Made', 'soy sauce, Self Made',
                    'shipping', 'steel, transport, Self Made', 'e-commerce, Self Made', 'mining',
                    'eyeglasses, Self Made', 'sensors, Self Made', 'Estee Lauder', 'discount brokerage, Self Made',
                    'oil, Self Made', 'gas, chemicals, Self Made', 'hedge funds, Self Made', 'vaccines, Self Made',
                    'mining', 'newspapers, TV network', 'software services, Self Made', 'internet media, Self Made',
                    'mining', 'smartphones, Self Made', 'restaurants, Self Made', 'e-commerce, Self Made',
                    'oil, gas, Self Made', 'investments, Self Made', 'paints, Self Made', 'BMW',
                    'medical devices, Self Made', 'eBay, PayPal, Self Made', 'H&M', 'money management',
                    'banking, tobacco', 'mining, Self Made', 'hedge funds, Self Made', 'banking, tobacco',
                    'automobiles, Self Made', 'pharmaceuticals, Self Made', 'medical devices, Self Made',
                    'casinos/hotels, Self Made', 'cheese', 'Apple, Disney', 'Google, Self Made',
                    'pharmaceuticals, Self Made', "Aldi, Trader Joe's", 'steel, telecom, investments, Self Made',
                    'wireless networking gear, Self Made', 'real estate, Self Made', 'petrochemicals, Self Made',
                    'diversified', 'real estate', 'hospitals, Self Made', 'coal, fertilizers, Self Made',
                    'Facebook, Self Made', 'video streaming, Self Made', 'media',
                    'finance, telecommunications, Self Made', 'food', 'messaging app, Self Made',
                    'chemicals, Self Made', 'beer, Self Made', 'fasteners, Self Made', 'Heineken',
                    'retail, investments, Self Made', 'batteries, automobiles, Self Made', 'hedge funds, Self Made',
                    'hedge funds, Self Made', 'e-cigarettes, Self Made', 'used cars, Self Made', 'banking, Self Made',
                    'investments, Self Made', 'investments, Self Made', 'hospitals, Self Made', 'Walmart',
                    'oil, banking, telecom, Self Made', 'automobiles, Self Made', 'real estate services, Self Made',
                    'smartphone screens, Self Made', 'real estate, Self Made', 'diversified', 'steel', 'auto parts',
                    'Zoom Video Communications, Self Made', 'real estate, Self Made', 'real estate',
                    'internet search, Self Made', 'construction', 'Facebook, Self Made',
                    'steel, investments, Self Made', 'hedge funds, Self Made', 'video surveillance, Self Made',
                    'software, Self Made', 'home improvement stores, Self Made', 'biotech, Self Made',
                    'video streaming app, Self Made', 'construction equipment, Self Made', 'software, Self Made',
                    'packaging', 'packaging', 'packaging', 'Airbnb, Self Made', 'real estate, Self Made',
                    'business software, Self Made', 'alcohol, real estate, Self Made', 'online games, Self Made',
                    'real estate', 'education, Self Made', 'fashion retail', 'mining, copper products, Self Made',
                    'hydraulic machinery, Self Made', 'ecommerce, Self Made', 'hedge funds, Self Made',
                    'batteries, Self Made', 'retail, media', 'commodities', 'coal, Self Made', 'vaccines',
                    'palm oil, shipping, property, Self Made', 'supermarkets', 'Twitter, Square, Self Made',
                    'education, Self Made', 'textiles, apparel, Self Made', 'e-commerce, Self Made',
                    'Airbnb, Self Made', 'venture capital, Self Made', 'Airbnb, Self Made', 'gaming, Self Made',
                    'semiconductors, Self Made', 'agribusiness, Self Made', 'Intel, Self Made',
                    'trading, investments, Self Made', 'Snapchat, Self Made', 'telecom, Self Made',
                    'semiconductors, Self Made', 'real estate', 'pharmaceuticals, Self Made', 'e-commerce, Self Made',
                    'cement, sugar, Self Made', 'beer, Self Made', 'investments, Self Made', 'hospitals, Self Made',
                    'steel, Self Made', 'real estate, Self Made', 'oil, Self Made', 'real estate, shipping',
                    'Snapchat, Self Made', 'banking, Self Made']
self_made_score = ['8', '8', None, '8', '8', '8', '9', '8', '9', None, None, None, None, '6', None, None, '1', '2', '4',
                   '8', None, '3', '8', None, '8', None, '5', '1', None, '8', None, None, None, None, None, '2', None,
                   None, None, '4', None, None, None, None, None, '9', None, '2', '2', None, None, None, None, None,
                   None, None, None, None, None, None, None, None, None, '5', '10', None, None, '8', None, None, '5',
                   None, None, None, None, None, None, None, '8', None, None, None, '8', None, '3', None, None, '8',
                   None, None, None, None, None, None, '2', '6', None, None, None, '8', None, None, None, None, None,
                   None, '8', None, '5', None, None, None, None, None, None, None, None, None, '8', '8', None, '9',
                   None, '9', None, '7', '1', None, None, None, None, '8', None, None, None, '8', None, None, None,
                   None, None, None, '8', None, None, '9', None, None, None, None, None, None, None, '8', None, '8',
                   None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, '3', '8',
                   None, None, None, '8', '8', '8', None, None, None, '8', '8', '8', None, '8', None, None, None, None,
                   None, None, None, None, None, None, None, '8', None]
philanthropy_score = ['1', '1', None, '4', '2', '5', '1', '1', '1', None, None, None, None, '2', None, None, '2', '1',
                      '1', '4', None, '2', '1', None, '2', None, '2', '2', None, '2', None, None, None, None, None,
                      None, None, None, None, None, None, None, None, None, None, '2', None, None, None, None, None,
                      None, None, None, None, None, None, None, None, None, None, None, None, '3', '1', None, None, '3',
                      None, None, '1', None, None, None, None, None, None, None, '2', None, None, None, '3', None, '2',
                      None, None, '3', None, None, None, None, None, None, '1', '2', None, None, None, '1', None, None,
                      None, None, None, None, '3', None, '2', None, None, None, None, None, None, None, None, None, '2',
                      '2', None, '1', None, '2', None, '1', '2', None, None, None, None, '3', None, None, None, None,
                      None, None, None, None, None, None, '2', None, None, '1', None, None, None, None, None, None,
                      None, None, None, '2', None, None, None, None, None, None, None, None, None, None, None, None,
                      None, None, None, '2', '2', None, None, None, None, '2', None, None, None, None, '5', None, '1',
                      None, '1', None, None, None, None, None, None, None, None, None, None, None, '1', None]
residence = ['Seattle, Washington', 'Austin, Texas', 'Paris, France', 'Medina, Washington', 'Palo Alto, California',
             'Omaha, Nebraska', 'Lanai, Hawaii', 'Palo Alto, California', 'Los Altos, California', 'Mumbai, India',
             'La Coruna, Spain', 'Paris, France', 'Hangzhou, China', 'Hunts Point, Washington', 'Shenzhen, China',
             'Mexico City, Mexico', 'Fort Worth, Texas', 'Bentonville, Arkansas', 'Bentonville, Arkansas',
             'New York, New York', 'Shanghai, China', 'Seattle, Washington', 'Franklin, Michigan', 'Ahmedabad, India',
             'Hillsboro, Oregon', 'Hangzhou, China', 'Wichita, Kansas', 'New York, New York', 'Tokyo, Japan',
             'Austin, Texas', 'Tokyo, Japan', 'Paris, France', 'Toronto, Canada', 'Germany', 'Shenzhen, China',
             'Las Vegas, Nevada', 'Foshan, China', 'Neckarsulm, Germany', 'Beijing, China', 'Brussels, Belgium',
             'New York, New York', 'New York, New York', 'Hong Kong', 'Nanyang, China', 'Hangzhou, China',
             'London, United Kingdom', 'Hong Kong, Hong Kong', 'The Plains, Virginia', 'Jackson, Wyoming',
             'Foshan, China', 'Moscow, Russia', 'Ningde, China', 'Shenzhen, China', 'Bad Homburg, Germany',
             'Moscow, Russia', 'Fuschl am See, Austria', 'Foshan, China', 'Schindellegi, Switzerland', 'Moscow, Russia',
             'Beijing, China', 'Mexico City, Mexico', 'Milan, Italy', 'Osaka, Japan', 'New York, New York',
             'Palm Beach, Florida', 'Moscow, Russia', 'Moscow, Russia', 'East Setauket, New York', 'Chongqing, China',
             'Perth, Australia', 'New York, New York', 'Delhi, India', 'Shenzhen, China', 'Santiago, Chile',
             'Beijing, China', 'Singapore, Singapore', 'Beijing, China', 'Moscow, Russia', 'New York, New York',
             'Singapore, Singapore', 'Frankfurt, Germany', 'Shenzhen, China', 'Honolulu, Hawaii', 'Stockholm, Sweden',
             'Milton, Massachusetts', 'Kudus, Indonesia', 'Perth, Australia', 'Greenwich, Connecticut',
             'Kudus, Indonesia', 'Hangzhou, China', 'Shanghai, China', 'Shenzhen, China', 'Hong Kong, Hong Kong',
             'Laval, France', 'Palo Alto, California', 'Atherton, California', 'Lianyungang, China',
             'Mulheim an der Ruhr, Germany', 'Moscow, Russia', 'San Jose, California', 'Beijing, China',
             'Wujiang, China', 'Bangkok, Thailand', 'Hong Kong, Hong Kong', 'Changsha, China', 'Moscow, Russia',
             'San Francisco, California', 'Beijing, China', 'New York, New York', None, None,
             'Dubai, United Arab Emirates', 'London, United Kingdom', 'Zurich, Switzerland', 'Kuenzelsau, Germany',
             'London, United Kingdom', 'Mumbai, India', 'Shenzhen, China', 'Greenwich, Connecticut',
             'Chicago, Illinois', 'Shenzhen, China', 'Tempe, Arizona', 'Mumbai, India', 'Indian Creek, Florida',
             'Moscow, Russia', 'Nashville, Tennessee', 'Jackson, Wyoming', 'London, United Kingdom', 'Baoding, China',
             None, 'Hong Kong, Hong Kong', 'Newport Beach, California', 'London, United Kingdom',
             'London, United Kingdom', 'Herzogenaurach, Germany', 'Santa Clara, California', 'Beijing, China',
             'Hong Kong, Hong Kong', 'Beijing, China', 'Mumbai, India', 'Singapore, Singapore', 'Moscow, Russia',
             'Palm Beach, Florida', 'Hong Kong, Hong Kong', 'Sydney, Australia', 'Eau Claire, Wisconsin',
             'Seoul, South Korea', 'Beijing, China', 'Changsha, China', 'Sydney, Australia', 'London, United Kingdom',
             'Surrey, United Kingdom', 'Newmarket, United Kingdom', 'San Francisco, California', 'Hong Kong, Hong Kong',
             'Incline Village, Nevada', 'Bangkok, Thailand', 'Seoul, South Korea', 'Singapore, Singapore',
             'Beijing, China', 'Aarhus, Denmark', 'Shenzhen, China', 'Changzhou, China', 'Moscow region, Russia',
             'Geneva, Switzerland', 'Ningde, China', 'Mexico City, Mexico', 'Mumbai, India', 'Yinchuan, China',
             'Pune, India', 'Hong Kong, Hong Kong', 'Grand Rapids, Michigan', 'San Francisco, California',
             'Tonghua, China', 'Ningbo, China', 'Beijing, China', 'San Francisco, California', 'Woodside, California',
             'San Francisco, California', 'Singapore, Singapore', 'Ningbo, China', 'Chengdu, China',
             'Woodside, California', 'Haverford, Pennsylvania', 'Venice, California', 'Zermatt, Switzerland',
             'Los Altos, California', 'Hamburg, Germany', 'Lianyungang, China', 'Hong Kong, Hong Kong',
             'Lagos, Nigeria', 'Sao Paulo, Brazil', 'Moscow, Russia', 'Rio de Janeiro, Brazil', 'Magnitogorsk, Russia',
             'Sydney, Australia', 'Moscow, Russia', 'Monte Carlo, Monaco', 'Los Angeles, California',
             'Bogota, Colombia']
citizenship = ['United States', 'United States', 'France', 'United States', 'United States', 'United States',
               'United States', 'United States', 'United States', 'India', 'Spain', 'France', 'China', 'United States',
               'China', 'Mexico', 'United States', 'United States', 'United States', 'United States', 'China',
               'United States', 'United States', 'India', 'United States', 'China', 'United States', 'United States',
               'Japan', 'United States', 'Japan', 'France', 'Canada', 'Germany', 'China', 'United States', 'China',
               'Germany', 'China', 'Italy', 'France', 'France', 'Hong Kong', 'China', 'China', 'United States',
               'Hong Kong', 'United States', 'United States', 'China', 'Russia', 'Hong Kong', 'China', 'Germany',
               'Russia', 'Austria', 'China', 'Germany', 'Russia', 'China', 'Mexico', 'Italy', 'Japan', 'United States',
               'United States', 'Russia', 'Russia', 'United States', 'China', 'Australia', 'United States', 'India',
               'China', 'Chile', 'China', 'Singapore', 'China', 'Russia', 'United States', 'Singapore', 'Germany',
               'Singapore', 'United States', 'Sweden', 'United States', 'Indonesia', 'Australia', 'United States',
               'Indonesia', 'China', 'China', 'Hong Kong', 'Hong Kong', 'France', 'United States', 'United States',
               'China', 'Germany', 'Russia', 'United States', 'China', 'China', 'Thailand', 'Hong Kong', 'China',
               'Russia', 'United States', 'China', 'United States', 'Czechia', 'Hong Kong', 'Russia', 'United Kingdom',
               'Brazil', 'Germany', 'Netherlands', 'India', 'China', 'United States', 'United States', 'China',
               'United States', 'India', 'United States', 'Russia', 'United States', 'United States', 'Russia', 'China',
               'China', 'Hong Kong', 'United States', 'United Kingdom', 'India', 'Germany', 'United States', 'China',
               'Hong Kong', 'China', 'Ireland', 'Brazil', 'Russia', 'United States', 'Hong Kong', 'Australia',
               'United States', 'South Korea', 'China', 'China', 'Australia', 'Sweden', 'Sweden', 'Sweden',
               'United States', 'Hong Kong', 'United States', 'Thailand', 'South Korea', 'Singapore', 'China',
               'Denmark', 'China', 'China', 'Russia', 'United Kingdom', 'China', 'Mexico', 'India', 'China', 'India',
               'Malaysia', 'United States', 'United States', 'China', 'China', 'China', 'United States',
               'United States', 'United States', 'Singapore', 'China', 'China', 'United States', 'United States',
               'United States', 'France', 'United States', 'Germany', 'China', 'Canada', 'Nigeria', 'Brazil', 'Russia',
               'Brazil', 'Russia', 'Australia', 'Russia', 'Israel', 'United States', 'Colombia']
marital_status = ['In Relationship', 'In Relationship', 'Married', 'Divorced', None, 'Widowed, Remarried',
                  'In Relationship', 'Married', 'Married', 'Married', 'Married', 'Married', None, 'Married', 'Married',
                  'Widowed', 'Divorced', 'Married', 'Married', 'In Relationship', None, 'Married', 'Married', 'Married',
                  'Married', 'Married', 'Married', 'Widowed', 'Married', 'Married', 'Married', 'Married', 'Divorced',
                  None, None, 'Widowed', 'Married', 'Married', None, 'Married', 'Married', 'Married', 'Widowed',
                  'Married', None, 'Married', 'Divorced', 'Divorced', 'Married', 'Married', 'Married', None, 'Married',
                  'Married', 'Married', 'Single', None, 'Married', 'Married', None, 'Married', 'Married', 'Married',
                  'Widowed, Remarried', 'Divorced', 'Married', 'Married', 'Married', 'Married', 'Widowed', 'Married',
                  'Married', None, 'Widowed', 'Married', 'Married', 'Married', 'Married', 'Married', 'Widowed',
                  'Married', None, 'Married', 'Married', 'Married', 'Married', 'Married', 'Married', 'Married',
                  'Married', 'Married', None, 'Married', None, 'Widowed', 'Married', 'Married', None, 'Married',
                  'Single', 'Divorced', 'Married', 'Married', 'Married', 'Married', 'Married', None, None, 'Widowed',
                  None, None, 'Single', 'Married', 'Married', 'Married', 'Married', 'Married', 'Married', 'Married',
                  'Divorced', 'Married', 'Married', 'Married', 'Married', 'Married', 'Married', 'Single', 'Divorced',
                  'Married', None, 'Married', 'Married', None, 'Married', 'Divorced', 'Married', 'Married', 'Widowed',
                  'Married', 'Married', 'Married', 'Married', 'Married', 'Married', 'Married', 'Married', 'Married',
                  None, 'Married', 'Married', None, None, None, 'Single', 'Divorced', 'Married', 'Married', 'Married',
                  None, None, 'Married', None, 'Married', 'Married', None, None, 'Married', 'Married', None, 'Widowed',
                  'Married', None, 'Single', None, 'Married', None, 'Married', 'Married', 'In Relationship', 'Married',
                  None, 'Married', 'Married', 'Married', 'Single', 'Married', 'Married', 'Married', None, 'Married',
                  'Divorced', 'Married', 'Single', 'Married', 'Married', 'Married', 'Married', 'Married', None,
                  'Married']
children = ['4', '6', '5', '3', '2', '3', '4', '1', '3', '3', '3', '2', None, '3', None, '6', None, '4', '3', '2', None,
            '4', '5', '2', '3', None, '2', '3', '2', '4', '2', '3', '4', None, None, '5', '3', '2', None, '2', '3', '2',
            '2', None, None, None, '5', '3', '3', None, '7', None, '2', '3', '7', '1', None, None, '3', None, None, '6',
            None, '2', '3', '1', '2', '3', '1', '4', '6', '1', None, '3', '2', None, None, '3', '3', '3', '1', None,
            '3', '3', '2', '3', '3', '4', '4', None, None, None, '5', None, '3', '2', '1', '1', None, None, '1', None,
            '5', '3', None, '2', None, None, '3', '4', '5', '2', None, '5', '3', '5', '3', None, '7', '3', None, None,
            '2', '2', '3', '3', None, '5', None, None, None, '7', None, '2', '4', '3', '1', '4', '4', '4', '1', '7',
            '3', '2', '2', '6', '2', None, '1', '2', None, None, None, None, '6', '10', '5', '2', None, None, '4', None,
            None, '4', None, None, '6', '3', None, '1', '8', None, None, None, None, None, '2', '2', None, None, None,
            '2', '2', '4', None, '4', None, None, None, '3', '3', '2', None, '5', '2', '2', '2', '4', '2', '5']
education = ['Bachelor of Arts/Science, Princeton University', 'Bachelor of Arts/Science, University of Pennsylvania',
             'Bachelor of Arts/Science, Ecole Polytechnique de Paris', 'Drop Out, Harvard University',
             'Drop Out, Harvard University',
             'Master of Science, Columbia University; Bachelor of Arts/Science, University of Nebraska Lincoln',
             'Drop Out, University of Chicago; Drop Out, University of Illinois, Urbana-Champaign',
             'Master of Science, Stanford University; Bachelor of Arts/Science, University of Michigan',
             'Master of Science, Stanford University; Bachelor of Arts/Science, University of Maryland, College Park',
             'Drop Out, Stanford University; Bachelor of Science in Engineering, University of Mumbai', None, None,
             None, 'Bachelor of Arts/Science, Harvard University; Drop Out, Stanford University',
             'Bachelor of Arts/Science, Shenzhen University',
             'Bachelor of Arts/Science, Universidad Nacional Autonoma de Mexico',
             'Bachelor of Arts/Science, Trinity University', 'Bachelor of Arts/Science, University of Arkansas',
             'Doctor of Jurisprudence, Columbia University; Bachelor of Arts/Science, University of Arkansas',
             'Master of Business Administration, Harvard Business School; Bachelor of Arts/Science, Johns Hopkins University',
             'Master, University of Wisconsin Madison; Bachelor of Arts/Science, Zhejiang University',
             'Bachelor of Arts/Science, Princeton University',
             'Bachelor of Arts/Science, Michigan State University; LLB, Wayne State University', None,
             'Master of Business Administration, Stanford Graduate School of Business; Bachelor of Arts/Science, University of Oregon',
             "Bachelor of Arts/Science, Hangzhou Teacher's Institute",
             'Bachelor of Arts/Science, Massachusetts Institute of Technology; Master of Science, Massachusetts Institute of Technology',
             None, 'Bachelor of Arts/Science, University of California, Berkeley',
             'Drop Out, The University of Texas at Austin', 'Bachelor of Arts/Science, Waseda University',
             'Drop Out, High School', 'Master of Arts, University of Cambridge', None, None,
             'Bachelor of Science, Hebrew University Jerusalem', None, None,
             'Bachelor of Engineering, Nankai University', None, None, None, 'Drop Out, High School', None,
             'Bachelor of Arts/Science, University of Electronic Science and Technology of China',
             'Master of Science, Columbia University; Master of Business Administration, Harvard Business School; Bachelor of Arts/Science, Moscow State University',
             None, 'Bachelor of Arts/Science, Bryn Mawr College',
             'Diploma, The Hotchkiss School; Bachelor of Arts/Science, Yale University',
             'Bachelor of Arts/Science, Ohio State University',
             'Bachelor of Arts/Science, Leningrad Institute of Economics; Master of Business Administration, University of Northumbria',
             'Doctorate, Chinese Academy of Social Sciences', 'Bachelor of Arts/Science, Wuhan U of  Science & Tec',
             'Master of Business Administration, International Institute for Management and Development',
             'Bachelor of Arts/Science, Moscow Institute of International Relations',
             'Master of Business Administration, University of Vienna', None, None,
             'Doctorate, Russian Academy of Economics; Bachelor of Arts/Science, Siberian Metallurgical Institute',
             'Graduate, Tsinghua University', None, None, None, 'Bachelor of Arts/Science, University of Pennsylvania',
             'Drop Out, New York University',
             'Bachelor of Science in Engineering, Azerbaijan Institute of Oil and Chemistry',
             'Bachelor of Arts/Science, Kuybyshev Engineering and Construction Institute',
             'Bachelor of Arts/Science, Massachusetts Institute of Technology; Doctorate, University of California, Berkeley',
             'Associate in Arts/Science, Guilin Medical University', None,
             'Bachelor of Arts/Science, Oxford University; Master of Arts, Oxford University',
             'Bachelor of Arts/Science, PSG College of Technology',
             'Bachelor of Arts/Science, Shenzhen University; Master of Arts, South China University of Technology',
             None, 'Bachelor of Science in Engineering, Wuhan University', None,
             'Bachelor of Arts/Science, Renmin University of China',
             'Bachelor of Arts/Science, Leningrad Mechanical Institute',
             'Master of Business Administration, Harvard Business School; Bachelor of Arts/Science, Yale University',
             None, 'Associate in Arts/Science, Technical University of Karlsruhe',
             'Bachelor of Science, University of Science and Technology of China',
             'Bachelor of Arts/Science, Tufts University', 'Associate in Arts/Science, University of Stockholm',
             'Master of Business Administration, Harvard Business School; Bachelor of Arts/Science, Hobart and William Smith',
             None, 'Bachelor of Arts/Science, University of Western Australia',
             'Master of Business Administration, Harvard Business School; Bachelor of Arts/Science, Long Island University',
             None, 'Master of Science, Yanshan University', 'EMBA, Nanjing University',
             'EMBA, Ceibs; Bachelor of Engineering, Tsinghua University; Master of Science in Engineering, Tsinghua University',
             None, None,
             'Master of Business Administration, Stanford Graduate School of Business; Bachelor of Arts/Science, University of Pennsylvania, The Wharton School',
             'Bachelor of Arts/Science, Princeton University; Doctorate, University of California, Berkeley; Master of Science, University of California, Berkeley',
             'Bachelor of Arts/Science, China Pharmaceutical University; Doctorate, Nanjing University', None,
             'Master, Finance Academy under the Government of the Russian Federation; Master of Laws, Moscow Institute of International Relations',
             'Bachelor of Arts/Science, University of California, San Diego; Master of Science, University of California, San Diego',
             'Bachelor of Engineering, Northwestern Polytechnical University', None, None,
             'Master of Business Administration, Columbia Business School',
             'Master of Business Administration, Hunan University',
             'Master of Science, Plekhanov Russian University of Economics', 'Drop Out, Harvard University',
             'Bachelor of Science, Tsinghua University', 'Drop Out, Syracuse University',
             'Bachelor of Arts/Science, University of Economics in Prague', None,
             'Master of Science, Saint Petersburg State University', None,
             'Bachelor of Arts/Science, Harvard University', None,
             'Bachelor of Arts/Science, Rijnlands Lyceum Wassenaar; Doctor of Jurisprudence, University of Leiden',
             None,
             'Master of Science, Beijing Non-Ferrous Research Institute; Bachelor of Arts/Science, Central South Industrial University of Technology',
             'Bachelor of Arts/Science, University of Pennsylvania, The Wharton School',
             'Bachelor of Arts/Science, Harvard University',
             'Master, China Europe International Business School; Bachelor of Arts/Economics, Tongji University',
             'Bachelor of Science, Stanford University',
             'Bachelor of Arts/Science, University of Mumbai; Master of Business Administration, University of Mumbai',
             'Drop Out, New York University; Bachelor of Arts/Science, Princeton University',
             'Bachelor of Arts/Science, Dagestan State University',
             'Bachelor of Arts/Science, Vanderbilt University; Medical Doctor, Washington University',
             'Bachelor of Arts/Science, Colorado College',
             'Bachelor of Arts/Science, Moscow Institute of Steel and Alloys',
             'Bachelor of Arts/Science, Hebei Province', None, None,
             'Bachelor of Arts/Science, University of Washington', None,
             "Bachelor of Arts/Science, St Xavier's College Calcutta", None,
             'Master of Engineering Management, China University of Mining and Technology; Bachelor of Engineering, Shandong Institute of Business and Technology',
             'Liaoning University', None,
             'Bachelor of Arts/Science, Peking University; Master of Arts, University at Buffalo', None,
             'Bachelor of Arts/Science, Harvard University', 'Bachelor of Arts/Science, Moscow State Law Academy',
             'Master of Business Administration, David A. Tepper School of Business; Bachelor of Arts/Science, University of Pittsburgh',
             'Bachelor of Arts/Science, Huazhong University of Science and Technology',
             'Bachelor of Arts/Science, University of New South Wales',
             'Bachelor of Arts/Science, University of Wisconsin, Eau Claire',
             'Bachelor of Arts/Science, Konkuk University; Master of Science, Konkuk University', None,
             'Bachelor of Arts/Science, Central South University',
             'Bachelor of Arts/Science, University of New South Wales', None, None, None,
             'Bachelor of Arts/Science, Rhode Island School of Design', None,
             'Bachelor of Engineering, Cornell University; Master of Business Administration, Samuel Curtis Johnson Graduate School of Management',
             None,
             'Doctorate, Korea Advanced Institute of Science and Technology; Master of Science, Korea Advanced Institute of Science and Technology; Bachelor of Arts/Science, Seoul National University',
             None, 'EMBA, China Europe International Business School', None, None, None,
             'Bachelor of Science, State University of Management',
             'Bachelor of Arts/Science, London School of Economics; Bachelor of Arts/Science, London School of Economics',
             'Bachelor of Technology, Hefei University of Technology',
             'Master of Business Administration, A. B. Freeman School of Business; Bachelor of Arts/Science, Tecnológico de Monterrey',
             'Master of Business Administration, London Business School; Bachelor of Arts/Science, University of Mumbai',
             'Master of Business Administration, Peking University',
             'Bachelor of Arts/Science, Pune University; Doctorate, Pune University',
             'Bachelor of Arts/Science, Raffles College', None, 'Drop Out, New York University', None, None,
             'Master of Business Administration, The Wharton School of the University of Pennsylvania',
             'Bachelor of Arts/Science, Harvard University',
             'Master of Business Administration, Harvard University; Bachelor of Arts/Science, Rice University; Master of Science, Rice University',
             'Bachelor of Arts/Science, Rhode Island School of Design',
             'Bachelor of Engineering, Shanghai Jiaotong University; Master of Business Administration, Stanford Graduate School of Business',
             'Bachelor of Science in Engineering, Tsinghua University', None,
             'Doctorate, California Institute of Technology; Bachelor of Arts/Science, University of California, Berkeley',
             'Bachelor of Science, SUNY Binghamton', 'Bachelor of Arts/Science, Stanford University', None,
             'Bachelor of Science in Engineering, Oregon State University; Master of Science in Engineering, Stanford University',
             'Master of Business Administration, Harvard Business School; Bachelor of Arts/Science, Harvard College',
             'Doctorate, Zhejiang University',
             'Bachelor of Arts/Science, Yale University; Doctor of Jurisprudence, Yale University',
             'Bachelor of Arts/Science, Al-Azhar University',
             'Bachelor of Arts/Science, Universidade Federal do Rio de Janeiro',
             'Bachelor of Arts/Science, Moscow Institute of Finance',
             'Masters of Public Health, Universidade Federal do Rio de Janeiro',
             'Bachelor of Science in Engineering, Magnitogorsk Mining\xa0and Metallurgical Institute',
             'Bachelor of Arts/Science, University of Leeds', 'Master of Science, Military Academy F.E.Dzerzhinsky',
             None, 'Bachelor of Science, Stanford University',
             'Bachelor of Arts/Science, National University of Colombia']

stats = [name, age, source_of_wealth, self_made_score, philanthropy_score, residence, citizenship, marital_status,
         children, education]
